
build:
	@echo Nothing to do for perl build

install:
	install -d ${DESTDIR}/usr/share/perl5/MCLURS
	install -D MCLURS/Snap.pm ${DESTDIR}/usr/share/perl5/MCLURS/Snap.pm

clean:
	@echo Nothing to do for perl clean
