#!/usr/bin/perl -w

use strict;
use lib "/home/pi/mclurs/perl";

BEGIN {
    $ENV{ PERL_ZMQ_BACKEND } = 'ZMQ::LibZMQ3';
}

use ZMQ;
use ZMQ::Constants qw(:all);

use MCLURS::Snap;

my $snapshot = "tcp://127.0.0.1:7777/";

my $zmq_ctx = ZMQ::Context->new() or die "Cannot create ZMQ context";
my $skt = $zmq_ctx->socket(ZMQ_REQ) or die "Cannot create ZMQ REQ socket";

$skt->connect($snapshot);

my $snap = MCLURS::Snap->new(skt => $skt, timeout => 1500);

dumphash($snap);

print "Transaction ", ($snap->_transact(cmd => 'z') || 'failed'), "\n";

dumphash($snap);

undef $snap;
$skt->close();
undef $zmq_ctx;

exit(0);

# ================================================================

sub dumphash {
    local $_;
    my $h = shift;
    for $_ ( keys %{$h} ) {
	print "\t$_:\t", $h->{$_}, "\n";
    }
}
